# Generated by Django 3.2.3 on 2021-06-23 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210623_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Cup Cakes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 11, 37, 45, 944703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 11, 37, 45, 944703, tzinfo=utc)),
        ),
    ]
