# Generated by Django 3.2.3 on 2021-06-24 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210623_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='BackgroundColor',
            new_name='LightBackgroundColor',
        ),
        migrations.AddField(
            model_name='carousel',
            name='DarkBackgroundColor',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 36, 7, 100026, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 14, 36, 7, 96020, tzinfo=utc)),
        ),
    ]
