# Generated by Django 3.2.3 on 2021-06-28 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210624_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=250)),
                ('phone_no', models.CharField(max_length=10)),
                ('query', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 9, 45, 57, 593967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 9, 45, 57, 589963, tzinfo=utc)),
        ),
    ]
