# Generated by Django 3.2.7 on 2021-10-12 14:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210628_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 14, 12, 25, 387532, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 14, 12, 25, 385530, tzinfo=utc)),
        ),
    ]
